# Generated by Django 4.2.13 on 2024-06-16 11:43

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_current_employee_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/', validators=[app.validators.validate_file_extension]),
        ),
    ]
