# Generated by Django 4.2.13 on 2024-07-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_uploadedfile_file_company_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
