# Generated by Django 4.2.13 on 2024-07-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_company_options_alter_uploadedfile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
    ]
