from django.urls import path
from app import views as app_views
from django.shortcuts import redirect
from allauth.account import views as allauth_views

urlpatterns = [
    path('user_list/', app_views.user_list, name='user_list'),
    path('accounts/signup/', app_views.add_user, name='account_signup'),
    path('accounts/logout/', app_views.Logout.as_view(), name='account_logout'),
    path('accounts/password/reset/', allauth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='account_password_reset'),
    path('accounts/password/reset/key/<uidb36>-<key>/', allauth_views.PasswordResetFromKeyView.as_view(template_name='password_reset_from_key.html')),
    path('accounts/password/reset/key/done/', allauth_views.PasswordResetFromKeyDoneView.as_view(template_name='password_reset_from_key_done.html')),
    path('accounts/password/reset/done/', allauth_views.PasswordResetDoneView.as_view(template_name='password_reset_from_key_done.html'), name='account_reset_password_done'),
    path('accounts/password/change/', allauth_views.PasswordChangeView.as_view(template_name='change_password.html')),
    path('accounts/confirm-email/', allauth_views.EmailVerificationSentView.as_view(template_name='confirm_email.html')),
    path('accounts/confirm-email/<key>/', allauth_views.ConfirmEmailView.as_view(template_name='confirm_email_key.html')),
    path('delete_user/<int:user_id>/', app_views.delete_user, name='delete_user'),
    path('accounts/login/', app_views.Login.as_view(), name='account_login'),
    path('upload_file/', app_views.upload_file, name='upload_file'),
    path('query_builder/', app_views.query_builder, name='query_builder'),

    # auto-complete urls
    path('autocomplete_name/',
         app_views.auto_complete_name,
         name='auto_complete_name'),
    path('autocomplete_domain/',
         app_views.auto_complete_domain,
         name='auto_complete_domain'),
    path('autocomplete_year_founded/',
         app_views.auto_complete_year_founded,
         name='auto_complete_year_founded'),
    path('autocomplete_industry/',
         app_views.auto_complete_industry,
         name='auto_complete_industry'),
    path('autocomplete_size_range/',
         app_views.auto_complete_size_range,
         name='auto_complete_size_range'),
    path('autocomplete_locality/',
         app_views.auto_complete_locality,
         name='auto_complete_locality'),
    path('autocomplete_country/',
         app_views.auto_complete_country,
         name='auto_complete_country'),
    path('autocomplete_linkedin_url/',
         app_views.auto_complete_linkedin_url,
         name='auto_complete_linkedin_url'),
    path('autocomplete_current_employee_estimate/',
         app_views.auto_complete_current_employee_estimate,
         name='auto_complete_current_employee_estimate'),
    path('autocomplete_total_employee_estimate/',
         app_views.auto_complete_total_employee_estimate,
         name='auto_complete_total_employee_estimate'),

    path('get_count/', app_views.CompanyApiView.as_view(), name='get_count'),
    path('', lambda request: redirect('account_login')),
    path('accounts/', lambda request: redirect('account_login')),
]